name: gimp
version: '2.10.18'
summary: GNU Image Manipulation Program
description: |
  Whether you are a graphic designer, photographer, illustrator, or scientist,
  GIMP provides you with sophisticated tools to get your job done. You can
  further enhance your productivity with GIMP thanks to many customization
  options and 3rd party plugins.
icon: gimp.png

grade: stable
confinement: strict
base: core18

architectures:
- build-on: amd64
- build-on: i386
- build-on: arm64
- build-on: armhf
- build-on: ppc64el
- build-on: s390x

layout:
  /etc/gimp:
    bind: $SNAP/etc/gimp
  /etc/ld.so.cache:
    bind-file: $SNAP_DATA/etc/ld.so.cache
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/babl-0.1:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/babl-0.1
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gegl-0.4:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gegl-0.4
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/evince/4/backends:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/evince/4/backends
  /usr/lib/gimp:
    bind: $SNAP/usr/lib/gimp
  /usr/lib/python2.7:
    bind: $SNAP/usr/lib/python2.7
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gvfs:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gvfs
  /usr/share/color:
    bind: $SNAP/usr/share/color
  /usr/share/ghostscript:
    bind: $SNAP/usr/share/ghostscript
  /usr/share/gimp:
    bind: $SNAP/usr/share/gimp
  /usr/share/mypaint-data:
    bind: $SNAP/usr/share/mypaint-data

plugs:
  ## DISABLED (1 of 4) because gtk2-common-themes only available on amd64
  gtk-2-engines:
    interface: content
    target: $SNAP/lib/gtk-2.0
    default-provider: gtk2-common-themes
  gtk-3-themes:
    default-provider: gtk-common-themes:gtk-3-themes
    interface: content
    target: $SNAP/data-dir/themes
  sound-themes:
    default-provider: gtk-common-themes:sound-themes
    interface: content
    target: $SNAP/data-dir/sounds
  gnome-3-28-1804:
    default-provider: gnome-3-28-1804:gnome-3-28-1804
    interface: content
    target: $SNAP/gnome-platform
  icon-themes:
    default-provider: gtk-common-themes:icon-themes
    interface: content
    target: $SNAP/data-dir/icons

slots:
  dbus-gimp:
    interface: dbus
    bus: session
    name: org.gimp.GIMP.UI

hooks:
  install:
    command-chain: [snap/command-chain/desktop-launch]
  post-refresh:
    command-chain: [snap/command-chain/desktop-launch]

environment:
  SNAP_DESKTOP_RUNTIME: $SNAP/gnome-platform
  GTK_EXE_PREFIX: $SNAP/usr
  GTK_USE_PORTAL: '1'
  GIMP2_LOCALEDIR: $SNAP/usr/share/locale
  LD_LIBRARY_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/lapack:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/blas:$LD_LIBRARY_PATH
  PYTHONPATH: $SNAP/usr/lib/python2.7:$SNAP/usr/lib/python2.7/site-packages:$PYTHONPATH
  FINAL_BINARY: $SNAP/usr/bin/gimp

apps:
  gimp:
    command: usr/bin/gimp
    command-chain:
    - snap/command-chain/desktop-launch
    - bin/check-ld-cache
    desktop: usr/share/applications/gimp.desktop
    common-id: org.gimp.GIMP
    slots:
    - dbus-gimp
    plugs:
    - cups-control
    - desktop
    - desktop-legacy
    - gsettings
    - home
    - network
    - opengl
    - removable-media
    - unity7
    - wayland
    - x11

parts:
  fix-pkgconfig-files:
    plugin: nil
    override-build: |
      cat <<EOF > $SNAPCRAFT_PART_INSTALL/fix-pkgconfig-files.sh
      for pcfile in \$SNAPCRAFT_PART_INSTALL/usr/lib/\$SNAPCRAFT_ARCH_TRIPLET/pkgconfig/*.pc \$SNAPCRAFT_PART_INSTALL/usr/lib/pkgconfig/*.pc \$SNAPCRAFT_PART_INSTALL/usr/local/lib/\$SNAPCRAFT_ARCH_TRIPLET/pkgconfig/*.pc \$SNAPCRAFT_PART_INSTALL/usr/local/lib/pkgconfig/*.pc; do
        sed -i -E "s~^((include|lib)dir=)/usr(/local)?~\1\\\${prefix}~g" \$pcfile || true
        sed -i -E "s~^((exec_)?prefix=)(/usr(/local)?)~\1/\3~" \$pcfile || true
      done
      EOF
      chmod +x $SNAPCRAFT_PART_INSTALL/fix-pkgconfig-files.sh
    prime:
    - -*

  fix-symlinks:
    # REF: https://unix.stackexchange.com/questions/100918/convert-absolute-symlink-to-relative-symlink-with-simple-linux-command
    plugin: nil
    override-build: |
      cat <<EOF > $SNAPCRAFT_PART_INSTALL/fix-symlinks.sh
      cd \$SNAPCRAFT_PART_INSTALL
      find . -lname '/*' |
      while read l ; do
        echo ln -sf \$(echo \$(echo \$l | sed 's|/[^/]*|/..|g')\$(readlink \$l) | sed 's/.....//') \$l
      done |
      sh
      EOF
      chmod +x $SNAPCRAFT_PART_INSTALL/fix-symlinks.sh
    prime:
    - -*

  gnome-extension:
    after: [patches]
    build-packages:
    - libgail-dev
    - libgtk-3-dev
    - libgtk2.0-dev
    stage-packages:
    - appmenu-gtk2-module
    - gtk2-engines
    - gtk2-engines-pixbuf
    - libatk-adaptor
    - libcanberra-gtk-module
    - libgail-common
    - libgtk2.0-0
    - libgtk2.0-bin
    - unity-gtk2-module
    - ibus-gtk
    plugin: make
    source: $SNAPCRAFT_EXTENSIONS_DIR/desktop
    source-subdir: gnome
    override-pull: |
      snapcraftctl pull
      # Remove GTK_PATH setting from launch script...
      # ... we use GTK_EXE_PREFIX instead to support both GTK2 *AND* 3 without conflict
      patch -Np3 < $SNAPCRAFT_STAGE/desktop-launch.patch
    override-build: |
      snapcraftctl build
      mkdir -p $SNAPCRAFT_PART_INSTALL/lib/gtk-2.0
      # Make GTK3 available via GTK_EXE_PREFIX expansion instead of GTK_PATH
      ln -sf ../../gnome-platform/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gtk-3.0 \
        $SNAPCRAFT_PART_INSTALL/usr/lib/gtk-3.0
      # Make GTK2 available via GTK_EXE_PREFIX expansion instead of GTK_PATH
      mv $SNAPCRAFT_PART_INSTALL/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gtk-2.0 \
        $SNAPCRAFT_PART_INSTALL/usr/lib/gtk-2.0
      ## DISABLED (2 of 4) because gtk2-common-themes only available on amd64
      # Make GTK2 engines available from content snap via GTK_EXE_PREFIX expansion
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/lib/gtk-2.0/2.10.0/engines
      ln -sf ../../../../lib/gtk-2.0/2.10.0/engines \
        $SNAPCRAFT_PART_INSTALL/usr/lib/gtk-2.0/2.10.0/

  patches:
    source: patches
    plugin: dump
    prime: [-*]

  scripts:
    source: scripts
    plugin: dump
    organize:
      build-ld-cache: bin/build-ld-cache
      check-ld-cache: bin/check-ld-cache

  gtk-locales:
    plugin: nil
    build-packages:
    - apt
    - dpkg
    override-pull: |
      set -eux
      apt download "language-pack-gnome-*-base"
    override-build: |
      set -eux
      for deb in *.deb; do dpkg-deb -x $deb .; done
      find usr/share/locale-langpack -type f -not -name "gtk20*.mo" -and -not -name "gtk30*.mo" -exec rm '{}' \;
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share
      cp -R usr/share/locale-langpack $SNAPCRAFT_PART_INSTALL/usr/share/

  # https://download.gimp.org/pub/babl
  babl:
    after:
    - fix-pkgconfig-files
    plugin: meson
    source: https://download.gimp.org/pub/babl/0.1/babl-0.1.74.tar.xz
    source-checksum: sha256/9a710b6950da37ada94cd9e2046cbce26de12473da32a7b79b7d1432fc66ce0e
    meson-parameters:
    - --prefix=/usr
    - -Dwith-docs=false
    build-environment:
      - CFLAGS: -O2 -pipe
      - CXXFLAGS: -O2 -pipe
    override-build: |
      snapcraftctl build
      $SNAPCRAFT_STAGE/fix-pkgconfig-files.sh
    build-packages:
    - git
    - gobject-introspection
    - libgirepository1.0-dev
    - liblcms2-dev
    - librsvg2-bin
    - librsvg2-dev
    - w3m
    prime:
    - -usr/include
    - -usr/lib/pkgconfig
    - -**/*.la

  # https://download.gimp.org/pub/gegl
  gegl:
    after:
    - babl
    - fix-pkgconfig-files
    source: https://download.gimp.org/pub/gegl/0.4/gegl-0.4.22.tar.xz
    source-checksum: sha256/1888ec41dfd19fe28273795c2209efc1a542be742691561816683990dc642c61
    plugin: meson
    meson-parameters:
    - --prefix=/usr
    build-environment:
    - CFLAGS: -O2 -pipe
    - CXXFLAGS: -O2 -pipe
    - XDG_DATA_DIRS: $SNAPCRAFT_STAGE/usr/share:/usr/local/share:/usr/share
    - GIO_MODULE_DIR: $SNAPCRAFT_STAGE/usr/lib/gio/modules
    override-build: |
      snapcraftctl build
      $SNAPCRAFT_STAGE/fix-pkgconfig-files.sh
    build-packages:
    - cmake
    - gobject-introspection
    - graphviz-dev
    - libavcodec-dev
    - libavformat-dev
    - libavutil-dev
    - libcairo2-dev
    - libexiv2-dev
    - libfftw3-dev
    - libgdk-pixbuf2.0-dev
    - libgexiv2-dev
    - libgirepository1.0-dev
    - libglib2.0-dev
    - libglu1-mesa-dev
    - libgs-dev
    - libjpeg8-dev
    - libjson-glib-dev
    - liblcms2-dev
    - liblensfun-dev
    - libluajit-5.1-dev
    - libopenjp2-7-dev
    - libopenexr-dev
    - libpango1.0-dev
    - libpng-dev
    - libpoppler-glib-dev
    - libraw-dev
    - librsvg2-dev
    - libsdl2-dev
    - libspiro-dev
    - libswscale-dev
    - libtiff5-dev
    - libv4l-dev
    - libwebp-dev
    - python-gi-dev
    - valac
    stage-packages:
    - graphviz
    - libamd2
    - libavcodec57
    - libavformat57
    - libavutil55
    - libbtf1
    - libcairo2
    - libcamd2
    - libccolamd2
    - libcholmod3
    - libcolamd2
    - libcxsparse3
    - libexiv2-14
    - libgdk-pixbuf2.0-0
    - libgexiv2-2
    - libgraphblas1
    - libgs9
    - libjpeg8
    - libklu1
    - liblapack3
    - liblcms2-2
    - libldl2
    - liblensfun1
    - libluajit-5.1-2
    - libopenexr22
    - libpng16-16
    - libpoppler-glib8
    - libraw16
    - librbio2
    - librsvg2-2
    - libsdl2-2.0-0
    - libspiro0
    - libspqr2
    - libswscale4
    - libtiff5
    - libumfpack5
    - libv4l-0
    - python-gobject-2
    - python-gi
    stage:
    - -**/*.la
    - -etc
    - -var/lib/ucf
    - -usr/sbin/update-mime
    - -usr/share/X11
    - -usr/share/alsa
    - -usr/share/applications
    - -usr/share/apport
    - -usr/share/apps
    - -usr/share/binfmts
    - -usr/share/bug
    - -usr/share/debhelper
    - -usr/share/doc
    - -usr/share/doc-base
    - -usr/share/fonts
    - -usr/share/glib-2.0
    - -usr/share/libdrm
    - -usr/share/libthai
    - -usr/share/lintian
    - -usr/share/locale
    - -usr/share/man
    - -usr/share/menu
    - -usr/share/mime
    - -usr/share/perl5
    - -usr/share/pixmaps
    - -usr/share/pkgconfig
    - -usr/share/python
    - -usr/share/xml
    prime:
    - -usr/include
    - -usr/lib/pkgconfig
    - -usr/share/vala

  # https://github.com/strukturag/libheif/releases
  libheif:
    source: https://github.com/strukturag/libheif/releases/download/v1.6.2/libheif-1.6.2.tar.gz
    plugin: autotools
    configflags:
    - --prefix=/usr
    - --disable-go
    - --disable-examples
    build-packages:
    - libde265-dev
    - libgdk-pixbuf2.0-dev
    - libjpeg8-dev
    - libpng-dev
    - libx265-dev
    stage-packages:
    - libde265-0
    - libgdk-pixbuf2.0-0
    - libjpeg8
    - libpng16-16
    - libx265-146
    override-build: |
      snapcraftctl build
      $SNAPCRAFT_STAGE/fix-pkgconfig-files.sh

  # https://github.com/mypaint/libmypaint/releases
  libmypaint:
    after:
    - fix-pkgconfig-files
    plugin: autotools
    source: https://github.com/mypaint/libmypaint/releases/download/v1.5.1/libmypaint-1.5.1.tar.xz
    source-checksum: sha256/aef8150a0c84ce2ff6fb24de8d5ffc564845d006f8bad7ed84ee32ed1dd90c2b
    build-packages:
    - gobject-introspection
    - intltool
    - libgirepository1.0-dev
    - libglib2.0-dev
    - libjson-c-dev
    - libjson-glib-dev
    configflags:
    - --prefix=/usr
    - --disable-static
    build-environment:
    - CFLAGS: -O2 -pipe
    - CXXFLAGS: -O2 -pipe
    - XDG_DATA_DIRS: $SNAPCRAFT_STAGE/usr/share:/usr/local/share:/usr/share
    override-build: |
      snapcraftctl build
      $SNAPCRAFT_STAGE/fix-pkgconfig-files.sh
    stage:
    - -**/*.la
    prime:
    - -usr/include
    - -usr/lib/pkgconfig

  # https://github.com/Jehan/mypaint-brushes/releases
  mypaint-brushes:
    after:
    - libmypaint
    source: https://github.com/Jehan/mypaint-brushes/archive/v1.3.0.tar.gz
    plugin: autotools
    configflags:
    - --prefix=/usr
    build-environment:
      - CFLAGS: -O2 -pipe
      - CXXFLAGS: -O2 -pipe

  # TODO: Think about splitting to a separate snap and consume via content interface?
  # # https://download.gimp.org/mirror/pub/gimp/help
  # gimp-help:
  #   after: [gimp]
  #   plugin: autotools
  #   source: https://download.gimp.org/mirror/pub/gimp/help/gimp-help-2.10.0.tar.bz2
  #   source-checksum: sha512/2f6d5e7cf0c3b4960c92074ef02d51a1d089c148f6453a66e453a3084cdede280f72c6b77d35f66777adbda8aa273ec2a472fb538142e51bb263c3077eec473a
  #   configflags:
  #   - --prefix=/usr
  #   build-environment:
  #   - PATH: /usr/bin:$PATH # Ensure system python is used, not from staging area
  #   build-packages:
  #   - dblatex
  #   - docbook2odf
  #   - pngcrush
  #   - pngnq
  #   - python
  #   - python-libxml2
  #   organize:
  #     root/stage/usr: usr
  #   prime:
  #   - -root

  # https://www.gimp.org/downloads
  gimp:
    after:
    - babl
    - desktop-settings-packages
    - gegl
    - gtk-locales
    - libheif
    - libmypaint
    - mypaint-brushes
    - patches
    plugin: autotools
    source: https://download.gimp.org/pub/gimp/v2.10/gimp-$SNAPCRAFT_PROJECT_VERSION.tar.bz2
    source-checksum: sha512/88990f2d70508b22f4acadeab6b687e20af19b765ebc6f245d0c99b3dd853fcd3d237c3b7607e50133aa95a1d71931069029dfd7ee94441ff419c542c141bc9f
    configflags:
    - --prefix=/usr
    - --sysconfdir=/etc
    - --with-bug-report-url=https://github.com/snapcrafters/gimp/issues/
    build-environment:
    - CFLAGS: -O2 -pipe
    - CXXFLAGS: -O2 -pipe
    - BABL_PATH: $SNAPCRAFT_STAGE/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/babl-0.1
    - GEGL_PATH: $SNAPCRAFT_STAGE/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gegl-0.4
    - XDG_DATA_DIRS: $SNAPCRAFT_STAGE/usr/share:/usr/local/share:/usr/share
    - PYTHON: /usr/bin/python2.7
    override-pull: |
      snapcraftctl pull
      sed -i 's|^Icon=.*|Icon=/usr/share/icons/hicolor/256x256/apps/gimp.png|' desktop/gimp.desktop.in.in
    override-build: |
      snapcraftctl build
      sed -i -E "s|^(.*python2?=).*|\1/snap/$SNAPCRAFT_PROJECT_NAME/current/usr/bin/python|" $SNAPCRAFT_PART_INSTALL/usr/lib/gimp/2.0/interpreters/pygimp.interp || true
      sed -i -E 's|^# \(mypaint-brush-path .*$|(mypaint-brush-path "/usr/share/mypaint-data/1.0/brushes:~/.mypaint/brushes")|' $SNAPCRAFT_PART_INSTALL/etc/gimp/2.0/gimprc
    build-packages:
    - automake
    - glib-networking
    - gobject-introspection
    - gtk-doc-tools
    - intltool
    - iso-codes
    - libaa1-dev
    - libart-2.0-dev
    - libbz2-dev
    - libcurl4-gnutls-dev
    - libexif-dev
    - libfftw3-dev
    - libgirepository1.0-dev
    - libglib2.0-dev
    - libgpm-dev
    - libgtk-3-dev
    - libgtk2.0-dev
    - libgudev-1.0-dev
    # - libheif-dev
    - libice-dev
    - libisocodes-dev
    - libjpeg8-dev
    - libmng-dev
    - libopenjp2-7-dev
    - libpoppler-glib-dev
    - libslang2-dev
    - libsm-dev
    - libtiff5-dev
    - libwebkitgtk-dev
    - libwebp-dev
    - libwmf-dev
    - libx11-dev
    - libxcursor-dev
    - libxmu-dev
    - libxpm-dev
    - libxt-dev
    - zlib1g-dev
    - python-dev
    - python-cairo-dev
    - python-gtk2-dev
    - xdg-utils
    - xsltproc
    - try:
      - libunwind-dev # not available in s390x
    stage-packages:
    - evince
    - ghostscript
    - gir1.2-gtk-2.0
    - gir1.2-poppler-0.18
    - glib-networking
    - gvfs
    - libaa1
    - libart-2.0-2
    - libbz2-1.0
    - libexif12
    - libfftw3-double3
    - libfftw3-single3
    - libgpm2
    # - libheif1
    - libjpeg8
    - libmng2
    - libopenjp2-7
    - libpoppler-glib8
    - libslang2
    - libwebkitgtk-1.0-0
    - libwebpmux3
    - libwmf0.2-7
    - libxmu6
    - libxpm4
    - libxt6
    - python-cairo
    - python-dev
    - python-gi
    - python-gtk2
    - rawtherapee
    - try:
      - libunwind8 # not available in s390x
      - libfftw3-long3 # only amd64 and i386
      - libfftw3-quad3 # only amd64 and i386
    stage:
    - -**/*.la
    - -etc/dbus-1
    - -etc/default
    - -etc/dictionaries-common
    - -etc/emacs
    - -etc/fonts
    - -etc/glvnd
    - -etc/gnome
    - -etc/gss
    - -etc/gtk-3.0
    - -etc/init.d
    - -etc/libblockdev
    - -etc/libpaper.d
    - -etc/mailcap.order
    - -etc/mime.types
    - -etc/rc*.d
    - -etc/sensors3.conf
    - -etc/systemd
    - -etc/ucf.conf
    - -etc/udisks2
    - -etc/X11
    - -sbin/cfdisk
    - -sbin/cgdisk
    - -sbin/fdisk
    - -sbin/fixparts
    - -sbin/gdisk
    - -sbin/parted
    - -sbin/partprobe
    - -sbin/sfddisk
    - -sbin/sgdisk
    - -usr/bin/aspell*
    - -usr/bin/dbus*
    - -usr/bin/desktop-file-*
    - -usr/bin/fc-*
    - -usr/bin/gtk-update-icon-cache
    - -usr/bin/ispell*
    - -usr/bin/mtrace
    - -usr/bin/rpcgen
    - -usr/bin/run-*
    - -usr/bin/select-default-iwrap
    - -usr/bin/update-*-database
    - -usr/bin/xdpyinfo
    - -usr/bin/xdriinfo
    - -usr/bin/xev
    - -usr/bin/xfd
    - -usr/bin/xfontsel
    - -usr/bin/xkill
    - -usr/bin/xlsatoms
    - -usr/bin/xlsclients
    - -usr/bin/xlsfonts
    - -usr/bin/xmessage
    - -usr/bin/xprop
    - -usr/bin/xvinfo
    - -usr/bin/xwininfo
    - -usr/lib/aspell
    - -usr/share/doc/libjpeg*
    - -usr/share/ghostscript
    - -var/cache
    - -var/lib/aspell
    - -var/lib/dbus
    - -var/lib/dictionaries-common
    - -var/lib/emacsen-common
    - -var/lib/ispell
    - -var/lib/systemd
    - -var/lib/ucf
    prime:
    - -usr/include
    - -usr/lib/pkgconfig

  # Ship a default set of GSettings schemas so that the correct theme is used
  # in Wayland sessions on Ubuntu (see https://forum.snapcraft.io/t/7806/3).
  desktop-settings-packages:
    after: [ gnome-extension ]
    plugin: nil
    build-packages:
    - libglib2.0-bin
    stage-packages:
    - gsettings-desktop-schemas
    - ubuntu-settings
    prime:
    - usr/share/glib-2.0/schemas/*

  desktop-settings-build:
    plugin: nil
    after: [ gimp, desktop-settings-packages ]
    override-prime: |
      set -eux
      glib-compile-schemas usr/share/glib-2.0/schemas

  cleanup:
    after: [ gimp, desktop-settings-build ]
    plugin: nil
    build-snaps:
    - core18
    - gnome-3-28-1804
    - gtk-common-themes
    ## DISABLED (3 of 4) because gtk2-common-themes only available on amd64
    - gtk2-common-themes
    override-prime: |
      set -eux
      for snap in "gnome-3-28-1804" "gtk-common-themes" "gtk2-common-themes"; do  # List all content-snaps you're using here
        cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
      done
      for CRUFT in bug lintian man; do
        rm -rf $SNAPCRAFT_PRIME/usr/share/$CRUFT
      done
      find $SNAPCRAFT_PRIME/usr/share/doc/ -type f -not -name 'copyright' -delete
      find $SNAPCRAFT_PRIME/usr/share -type d -empty -not -path "$SNAPCRAFT_PRIME/usr/share/gimp/*" -delete
